### Users Endpoints

## Get All Users
GET http://localhost:8765/user-service/user/allUsers

###
## Create User
POST http://localhost:8765/user-service/user/create
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@teste.com"
}

###
## Edit User
POST http://localhost:8765/user-service/user/edit/6
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@teste.com"
}

###
## Delete User
POST http://localhost:8765/user-service/user/delete/6
