### Users Endpoints

## Get All Users
GET http://localhost:8765/user-service/user/allUsers

###
## Create User
POST http://localhost:8765/user-service/user/create
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@teste.com"
}

###
## Edit User
POST http://localhost:8765/user-service/user/edit/6
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@teste.com"
}

###
## Delete User
POST http://localhost:8765/user-service/user/delete/10



### ContactBook Endpoints

## Get All ContactBooks
GET http://localhost:8765/contactbook-service/contactbook/getAllContactBooks

###

## Create ContactBook
POST http://localhost:8765/contactbook-service/contactbook/create

###

## Delete ContactBook
POST http://localhost:8765/contactbook-service/contactbook/delete/10

###

## Add Contact to ContactBook
POST http://localhost:8765/contactbook-service/contactbook/addContact/1/1

### Contact Endpoints

## Get All Contact
GET http://localhost:8765/contact-service/contact/getAllContacts

###

## Create Contact
POST http://localhost:8765/contact-service/contact/create/1
Content-Type: application/json

{
  "name": "Teste4",
  "email": "teste@teste.com",
  "phoneNumber": "teste"
}

###

## Edit Contact
POST http://localhost:8765/contact-service/contact/edit/1
Content-Type: application/json

{
  "name": "Teste2",
  "email": "teste@teste.com",
  "phoneNumber": "teste"
}

###

## Delete Contact
POST http://localhost:8765/contact-service/contact/delete/1

### Calendar Endpoints

## Get All Calendars
GET http://localhost:8765/calendar-service/calendar/getAllCalendars

###

## Create Calendar
POST http://localhost:8765/calendar-service/calendar/create

###

## Delete Calendar
POST http://localhost:8765/calendar-service/calendar/delete/2

### Appointments Endpoints

## Get All Appointments
GET http://localhost:8765/appointment-service/appointment/getAllAppointments

###

## Create Appointment
POST http://localhost:8765/appointment-service/appointment/create
Content-Type: application/json

{
  "name": "reuniao",
  "date": "2024-01-17 00:10:49.000Z",
  "descricao": "apresentacao"
}

###

## Delete Appointment

POST http://localhost:8765/appointment-service/appointment/delete/2

## Edit Appointment

###

POST http://localhost:8765/appointment-service/appointment/edit/1
Content-Type: application/json

{
  "name": "reuniao2",
  "date": "2024-01-17 00:10:49.000Z",
  "descricao": "apresentacao2"
}

###

## Add Apointment

POST http://localhost:8765/appointment-service/appointment/create/1
Content-Type: application/json

{
  "name": "reuniao",
  "date": "2024-01-17 00:10:49.000Z",
  "descricao": "apresentacao"
}
